name: Maven Build & Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Prepare ZIP archive
      env:
        TAG_NAME: ${{ github.ref_name }}
      run: |
        mkdir release
        cp target/server-${TAG_NAME}.jar release/
        cp -r .config release/
        cp README.md LICENSE release/
        cd release
        zip -r ../server-release.zip .

    - name: Upload release ZIP
      uses: softprops/action-gh-release@v1
      with:
        files: |
          server-release.zip
